// flow-typed signature: e480e8ee2fd9498cdfa59c77865f838b
// flow-typed version: <<STUB>>/express-async-handler_v^1.1.4/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-async-handler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-async-handler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-async-handler/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-async-handler/index' {
  declare module.exports: $Exports<'express-async-handler'>;
}
declare module 'express-async-handler/index.js' {
  declare module.exports: $Exports<'express-async-handler'>;
}
declare module 'express-async-handler/test.js' {
  declare module.exports: $Exports<'express-async-handler/test'>;
}
