// flow-typed signature: 0cf52ecc65e10eb8d1685ad2cd447986
// flow-typed version: <<STUB>>/sanitize.css_v^8.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
